export default {
    LOGIN: 'LOGIN',
    ADD_USER: 'ADD_USER',
    GET_USERS: 'GET_USERS',
    DELETE_USER: 'DELETE_USER',
    MODIFY_PASSWORD: 'MODIFY_PASSWORD',
    GET_PROVIDERS: 'GET_PROVIDERS',
    ADD_PROVIDER: 'ADD_PROVIDER',
    DELETE_PROVIDER: 'DELETE_PROVIDER',
    MODIFY_PROVIDER: 'MODIFY_PROVIDER',
    GET_BILLS: 'GET_BILLS',
    ADD_BILL: 'ADD_BILL',
    MODIFY_BILL: 'MODIFY_BILL',
    DELETE_BILL: 'DELETE_BILL',
    GET_BILLS_BY_PROVIDER_NAME: 'GET_BILLS_BY_PROVIDER_NAME'
};
