export default {
    LOGIN: 'LOGIN',
    ADD_USER: 'ADD_USER',
    GET_USERS: 'GET_USERS',
    DELETE_USER: 'DELETE_USER',
    MODIFY_PASSWORD: 'MODIFY_PASSWORD',
    GET_PROVIDERS: 'GET_PROVIDERS',
    ADD_PROVIDER: 'ADD_PROVIDER',
    DELETE_PROVIDER: 'DELETE_PROVIDER',
    MODIFY_PROVIDER: 'MODIFY_PROVIDER',
    GET_ORDERS: 'GET_ORDERS',
    ADD_ORDER: 'ADD_ORDER',
    MODIFY_ORDER: 'MODIFY_ORDER',
    DELETE_ORDER: 'DELETE_ORDER',
    GET_ORDERS_BY_PROVIDER_NAME: 'GET_ORDERS_BY_PROVIDER_NAME'
};
